db:
    image: postgres:9.4
    container_name: postgres-container
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'

server:
    build: .
    container_name: wildfly-container
    ports:
        - "8080:8080"
